package com.fiap.tech_challenge.core.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
@Schema(description = "Standard error response following RFC 7807")
public class ErrorResponseDto {
    @Schema(description = "URI identifying the error type", example = "about:blank")
    private String type;

    @Schema(description = "Short, human-readable summary of the problem", example = "Bad Request")
    private String title;

    @Schema(description = "HTTP status code generated by the origin server", example = "400")
    private int status;

    @Schema(description = "Detailed error message", example = "Invalid email format")
    private String detail;

    @Schema(description = "URI of the request that caused the error", example = "/api/v1/users")
    private String instance;

}
